
GET http://localhost:3000/api/v1/points

###
GET http://localhost:3000/api/v1/points?time=2023-12-24T21:08:43.121Z

###
GET http://localhost:3000/api/v1/points/4a3d9aaa-608c-49a7-a004-66305ad4ab50

###
POST http://localhost:3000/api/v1/points
content-type: application/json

{
  "lat": 45.17,
  "long": 55.75
}

###
PATCH http://localhost:3000/api/v1/points/31520713-7026-4cd1-8ae2-6348e0d764d8
content-type: application/json

{
  "lat": 4.12
}

###
DELETE http://localhost:3000/api/v1/points/61dbae02-c147-4e28-863c-db7bd402b2d6 HTTP/1.1

