GET http://localhost:3000/api/v1/points?time=2023-12-18T01:43:24.519Z

###
GET http://localhost:3000/api/v1/points/4a3d9aaa-608c-49a7-a004-66305ad4ab50

###
PATCH http://localhost:3000/api/v1/points/2

###
DELETE http://localhost:3000/api/v1/points/2 HTTP/1.1

###
POST http://localhost:3000/api/v1/points HTTP/1.1
header name: header value

content